fix: move fees to order factory
ImpeccableHQ/stackly pull request #29
Opened 2023-04-24 16:38 UTC by berteotti

- Update tests
- Update README

2023-04-27 10:31 UTC, NelsonGaldeman requested changes
Good PR, core changes are good. Just a few small comments here and there but good job man!

2023-04-27 10:31 UTC, NelsonGaldeman commented on packages/contracts/src/DCAOrder.sol
> +    uint256 _totalAmount,
I might be nitpicky here but can we just call it `amount`?

2023-04-27 10:31 UTC, NelsonGaldeman commented on packages/contracts/src/OrderFactory.sol
> +  function createProxy(address _singleton, bytes memory _initializer, uint256 _saltNonce)
Good call here!

2023-04-27 10:31 UTC, NelsonGaldeman commented on packages/contracts/src/OrderFactory.sol
> +    IERC20(_sellToken).transferFrom(msg.sender, address(this), (_totalAmount * protocolFee) / 100);
I'm not entirely sure weather it's best (gas-wise) to re-do the math here or to store `feeAmount` and substract from the total (which is already in storage) every time. Substraction should be cheaper than multiplication & division. Can you do some profiling and update accordingly?

2023-04-27 10:31 UTC, NelsonGaldeman commented on packages/contracts/src/OrderFactory.sol
> +  function createOrderWithNonce(
Can you update the SDK/frontend to reflect contract changes in this same PR? We should re-deploy the contract before this PR is merged so it won't break

2023-04-27 15:11 UTC, berteotti commented on packages/contracts/src/OrderFactory.sol
> +  function createOrderWithNonce(
Will do it!

2023-04-27 15:21 UTC, berteotti commented on packages/contracts/src/OrderFactory.sol
> +    IERC20(_sellToken).transferFrom(msg.sender, address(this), (_totalAmount * protocolFee) / 100);
Did the math and it saves gas doing saving the `feeAmount`. Good tip!

2023-04-27 15:40 UTC, berteotti commented on packages/contracts/src/OrderFactory.sol
> +    IERC20(_sellToken).transferFrom(msg.sender, address(this), (_totalAmount * protocolFee) / 100);
Fixed

2023-04-27 15:40 UTC, berteotti commented on packages/contracts/src/DCAOrder.sol
> +    uint256 _totalAmount,
Fixed

2023-05-04 10:15 UTC, NelsonGaldeman approved these changes
LGTM

2023-05-04 10:17 UTC, merged