fix: dust tokens after last order
ImpeccableHQ/stackly pull request #43
Opened 2023-05-05 11:35 UTC by berteotti

This PR fixes the dust tokens after last order by setting the last slot sell amount as the total amount of left tokens.

2023-05-05 14:14 UTC, NelsonGaldeman requested changes
I added a comment on gas optimizations

2023-05-05 14:14 UTC, NelsonGaldeman commented on packages/contracts/src/DCAOrder.sol
> +    if (lastSlot == orderExecutionTime) {
Calling `currentSlot` is expensive here, it also calls `orderSlots` again, which is a loop.

Can't you just do some math checks against `block.timestamp` using `endTime` and `interval` to determine if it's the last slot?

It should be a lot cheaper.

2023-05-05 17:22 UTC, berteotti commented on packages/contracts/src/DCAOrder.sol
> +    if (lastSlot == orderExecutionTime) {
Good suggestion. Thought about it but was harder to read.

2023-05-08 18:11 UTC, NelsonGaldeman commented
General comments for next PRs:

- All commits should follow this general convention: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format (body & scope are optional)
- There is 2 commits with the same name, either the summery is too generic or they should be one commit (sometimes it's ok to revert a commit, make a new bigger one and do a force push)

2023-05-09 10:25 UTC, berteotti commented
> General comments for next PRs:
> 
> * All commits should follow this general convention: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format (body & scope are optional)
> * There is 2 commits with the same name, either the summery is too generic or they should be one commit (sometimes it's ok to revert a commit, make a new bigger one and do a force push)

Totally agree with you here. But in this case, here at Swapr we are used to squash all the commits into a commit that follows the rules you shared and then merge. Is it okay for you this approach? @NelsonGaldeman

2023-05-09 12:59 UTC, NelsonGaldeman commented
> Totally agree with you here. But in this case, here at Swapr we are used to squash all the commits into a commit that follows the rules you shared and then merge. Is it okay for you this approach? @NelsonGaldeman

My problem with that approach is that in the same PR may not want everything in one commit (post-squashing) as there might be different kind of atomic changes that add up into having a full PR. Nothing against single-commit PRs, but it doesn't apply for all cases. I think it's easier/cleaner to do the commits right the first time rather than patching it on merge

2023-05-10 08:56 UTC, berteotti commented
> c6d84ce

What about this commit? I don't want to merge this commit as it was a final step to reach the goal of the original commit. I would rather squash it and rename the commit. I understand that it might not fit every case, but in my view every PR should be atomic on it's own. If we are doing many things in one PR, there's something wrong. Although I agree with you that squash might not fit in every case, I think in this PR we can squash it. What do you think? @NelsonGaldeman

2023-05-10 10:21 UTC, NelsonGaldeman commented
For that particular commit, you could have done the following:

```
$ git reset HEAD~
$ git add {...relevant files...}
$ git commit {...}
$ git push --force
```

Then the commit will be showing only the latest change from development.

A PR being atomic doesn't imply it has to be one commit.

e.g. a PR with 3 commits that are not atomic and breaking the code individually but all three together work, post-merge, there is no way to tell where did the PR start and finish from the commit list, so in case you need to revert some changes, if you pick the wrong one you could end up with a broken code.

In contrast, if every commit is atomic, by heritance, the PR will always be atomic too. But in case of need to revert something, it won't break anything whatever commit you choose to point the revertion to.

I'm not saying squashing is wrong, it's not! But it's also easier for reviewer to have a clean commit list of changes and diff per commit.

e.g. Bitcoin maintainers have done a very good job keeping this clean: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#committing-patches

some PR examples [1](https://github.com/bitcoin/bitcoin/pull/27570/commits), [2](https://github.com/bitcoin/bitcoin/pull/27488/commits), [3](https://github.com/bitcoin/bitcoin/pull/27482/commits).

2023-05-10 16:31 UTC, berteotti commented
I think it's cleaner now, did a squash before the merge but I think we can do squash & merge if there space to do it. The first PR you shown did a squash & merge, for example.

2023-05-11 09:50 UTC, NelsonGaldeman commented
> I think it's cleaner now, did a squash before the merge but I think we can do squash & merge if there space to do it. The first PR you shown did a squash & merge, for example.

The example Bitcoin PRs were to point out the commits org/messaging and sepaartion within the PR though. Sorry if it was misleading!

This PR is ok to me, there is only one comment left to be addressed and can be merged (not sure if you seen it)

2023-05-11 10:06 UTC, NelsonGaldeman requested changes
Also, could you add a test-case where it would have left dust using the previous code? To prove it works.

2023-05-11 10:06 UTC, NelsonGaldeman commented on packages/contracts/src/DCAOrder.sol
> +    uint256 currentTime = block.timestamp;
`block.timestamp` is loaded from the block header within the TX, there is a specific opcode (0x42) called `TIMESTAMP` for it, which costs 2 gas units.

Storing a uint256, as of now, uses MLOAD opcode, that costs 3 units of gas. Also, depending if it needs to do a memory expansion or not, it might cost another extra 3 units.

Then, you access it three times on code logic, calling MLOAD opcode, costing 3 gas units each. So even without memory extension it's costing 14 gas units, compared to 6 it would cost to access `block.timestamp` directly three times!

2023-05-11 10:45 UTC, berteotti commented on packages/contracts/src/DCAOrder.sol
> +    uint256 currentTime = block.timestamp;
Should we also address this in `currentSlot()`

2023-05-11 15:14 UTC, NelsonGaldeman commented on packages/contracts/src/DCAOrder.sol
> +    uint256 currentTime = block.timestamp;
Yes, good shout. Missed that one

2023-05-12 12:26 UTC, NelsonGaldeman requested changes
Just seen this too

2023-05-12 12:26 UTC, NelsonGaldeman commented on packages/contracts/src/DCAOrder.sol
>      if (block.timestamp >= slots[slots.length - 1] && block.timestamp < endTime) {
Can't this be removed and then the loop iterates over all the slots? It simplifies the code and I don't see any downsides over efficiency.

2023-05-12 13:34 UTC, berteotti commented on packages/contracts/src/DCAOrder.sol
>      if (block.timestamp >= slots[slots.length - 1] && block.timestamp < endTime) {
The last slot is the most expensive to reach, but adding this `if` raises the cost for getting all the slots (minus the last one). Is it worthy to remove this last slot verification?

2023-05-15 17:50 UTC, NelsonGaldeman commented on packages/contracts/src/DCAOrder.sol
>      if (block.timestamp >= slots[slots.length - 1] && block.timestamp < endTime) {
All slots are going to be called the same amount of times per TX so it doesn't save any gas overall having to pay for that condition every time, it also makes the code less readable for no good reason.

Also, because of the `break` you don't even pay for the extra loop until it's last slot turn, but you pay for the if condition on every TX.

So yeah, not worth it!

2023-05-18 14:33 UTC, NelsonGaldeman commented on packages/contracts/src/DCAOrder.sol
>      if (block.timestamp >= slots[slots.length - 1] && block.timestamp < endTime) {
As discussed offchain, the `endTime` for the last slot cannot be easily pulled without more conditions within the loop so gas-wise current approach is ok.

2023-05-18 14:38 UTC, NelsonGaldeman approved these changes
LGTM. Thanks Leo.

2023-05-18 14:38 UTC, merged